=== HuzarO/l2horizon-telnet-ext/CustomQuestsExt/decompiled/buffer_skills.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT list (category+)>

<!ELEMENT category (buff+)>
<!ATTLIST category
	type CDATA #REQUIRED
>

<!ELEMENT buff EMPTY>
<!ATTLIST buff
	id CDATA #REQUIRED
	level CDATA #IMPLIED
	price CDATA #IMPLIED
	desc CDATA #IMPLIED
>

=== HuzarO/l2horizon-telnet-ext/CustomQuestsExt/decompiled/buffer_skills.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "buffer_skills.dtd">
<list>
	<!-- DEFAULT: buff id="skill id" level="max level" price="0" desc="" -->
	<category type="Buffs">
		<buff id="1035" desc="Increases resistance to mental attacks."/><!-- Mental Shield -->
		<buff id="1036" desc="Increases M. Def."/><!-- Magic Barrier -->
		<buff id="1040" desc="Increases P. Def."/><!-- Shield -->
		<buff id="1045" desc="Increases maximum HP."/><!-- Blessed Body -->
		<buff id="1048" desc="Increases maximum MP."/><!-- Blessed Soul -->
		<buff id="1059" desc="Increases M. Atk."/><!-- Empower -->
		<buff id="1062" desc="Reduces def. and increase atk. power."/><!-- Berserker Spirit -->
		<buff id="1068" desc="Increases P. Atk."/><!-- Might -->
		<buff id="1077" desc="Increases critical attack rate."/><!-- Focus -->
		<buff id="1078" desc="Increases magic concentration."/><!-- Concentration -->
		<buff id="1085" desc="Increases Casting Spd."/><!-- Acumen -->
		<buff id="1086" desc="Increases Atk. Spd."/><!-- Haste -->
		<buff id="1087" desc="Increases Evasion."/><!-- Agility -->
		<buff id="1204" desc="Increases Speed."/><!-- Wind Walk -->
		<buff id="1240" desc="Increases Accuracy."/><!-- Guidance -->
		<buff id="1242" desc="Increases critical attack."/><!-- Death Whisper -->
		<buff id="1243" desc="Increases shield defense rate."/><!-- Bless Shield -->
		<buff id="1268" desc="Restores HP using inflicted damage."/><!-- Vampiric Rage -->
		<buff id="1303" desc="Increases crit. rate of magic attacks."/><!-- Wild Magic -->
		<buff id="1304" desc="Increases shield defense power."/><!-- Advanced Block -->
		<buff id="1388" desc="Increases P. Atk."/><!-- Greater Might -->
		<buff id="1389" desc="Increases P. Def."/><!-- Greater Shield -->
		<buff id="1397" desc="Decreases MP consumption rate."/><!-- Clarity -->
		<buff id="1257" desc="Makes body lighter." /><!-- Decrease Weight -->
	</category>
	<category type="Dances">
		<buff id="271" desc="Increases P. Atk."/><!-- Dance of the Warrior -->
		<buff id="272" desc="Increases Accuracy."/><!-- Dance of Inspiration -->
		<buff id="273" desc="Increases M. Atk."/><!-- Dance of the Mystic -->
		<buff id="274" desc="Increases critical damage."/><!-- Dance of Fire -->
		<buff id="275" desc="Increases attack speed."/><!-- Dance of Fury -->
		<buff id="276" desc="Increases Casting Spd."/><!-- Dance of Concentration -->
		<buff id="277" desc="Sacred power to physical attack."/><!-- Dance of Light -->
		<buff id="307" desc="Increases water resistance."/><!-- Dance of Aqua Guard -->
		<buff id="309" desc="Increases earth resistance."/><!-- Dance of Earth Guard -->
		<buff id="310" desc="Restores HP by inflicted damage."/><!-- Dance of the Vampire -->
		<buff id="311" desc="Increases resistance to terrain damage."/><!-- Dance of Protection -->
		<buff id="365" desc="Increases rate of magic crit. damage."/><!-- Siren's Dance -->
		<buff id="366" desc="Gives invis to agressive monsters."/><!-- Dance of Shadows -->
	</category>
	<category type="Songs">
		<buff id="264" desc="Increases P. Def."/><!-- Song of Earth -->
		<buff id="265" desc="Increases HP regeneration."/><!-- Song of Life -->
		<buff id="266" desc="Increases Evasion."/><!-- Song of Water -->
		<buff id="267" desc="Increases M. Def."/><!-- Song of Warding -->
		<buff id="268" desc="Increases movement."/><!-- Song of Wind -->
		<buff id="269" desc="Increases critical rate."/><!-- Song of Hunter -->
		<buff id="270" desc="Increases resistance to dark magic."/><!-- Song of Invocation -->
		<buff id="304" desc="Increases maximum HP."/><!-- Song of Vitality -->
		<buff id="305" desc="Reflects damage received."/><!-- Song of Vengeance -->
		<buff id="306" desc="Increases resistance to fire."/><!-- Song of Flame Guard -->
		<buff id="308" desc="Increases resistance to wind."/><!-- Song of Storm Guard -->
		<buff id="349" desc="Decreases re-use time."/><!-- Song of Renewal -->
		<buff id="363" desc="Increases MP regeneration rate."/><!-- Song of Meditation -->
		<buff id="364" desc="Decreases re-use time of physical skills."/><!-- Song of Champion -->
	</category>
	<category type="Resists">
		<buff id="1182" desc="Increases resistance to water attack."/><!-- Resist Aqua -->
		<buff id="1189" desc="Increases resistance to wind attack."/><!-- Resist Wind -->
		<buff id="1191" desc="Increases resistance to fire attack."/><!-- Resist Fire -->
		<buff id="1259" desc="Increases resistance to stun attack."/><!-- Resist Shock -->
		<buff id="1352" desc="Increases resistance to elements."/><!-- Elemental Protection -->
		<buff id="1353" desc="Increases resistance to dark attack."/><!-- Divine Protection -->
		<buff id="1354" desc="Increases resistance to de-buff attack."/><!-- Arcane Protection -->
		<buff id="1392" desc="Increases resistance to holy attack."/><!-- Holy Resistance -->
		<buff id="1393" desc="Increases resistance to dark attack."/><!-- Unholy Resistance -->
	</category>
	<category type="Extras">
		<buff id="1355" desc="Increases mage abilities."/><!-- Prophecy of Water -->
		<buff id="1356" desc="Increases fighter abilities."/><!-- Prophecy of Fire -->
		<buff id="1357" desc="Increases dagger abilities."/><!-- Prophecy of Wind -->
		<buff id="1363" desc="Increases combat abilities."/><!-- Chant of Victory -->
		<buff id="1413" desc="Increases mage abilities."/><!-- Magnus' Chant -->
		<buff id="4699" desc="Increases crt. dmg. amount and power."/><!-- Blessing of Queen -->
		<buff id="4700" desc="Increases p. atk. and accuracy."/><!-- Gift of Queen -->
		<buff id="4702" desc="Increases MP regeneration."/><!-- Blessing of Seraphim -->
		<buff id="4703" desc="Reduces magic skill recovery time.."/><!-- Gift of Seraphim -->
	</category>
</list>
